// index.js
const functions = require("firebase-functions");
const { onDocumentCreated } = require("firebase-functions/v2/firestore");
const { onSchedule } = require("firebase-functions/v2/scheduler");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore, FieldValue, Timestamp } = require("firebase-admin/firestore");
const nodemailer = require("nodemailer");
const Imap = require("imap");
require("dotenv").config();
const { simpleParser } = require("mailparser");

// ✅ Initialize the app and get Firestore
initializeApp();
const db = getFirestore();

const imapUser = process.env.IMAP_USER;
const imapPass = process.env.IMAP_PASS;

// ✅ Read directly from .env
const FROM_EMAIL = process.env.OUTLOOK_EMAIL;
const FROM_PASS = process.env.OUTLOOK_PASSWORD;

if (!FROM_EMAIL || !FROM_PASS) {
  throw new Error("Missing OUTLOOK_EMAIL or OUTLOOK_PASSWORD in .env");
}

// ✅ Office365 SMTP transporter
const transporter = nodemailer.createTransport({
  host: "smtp.office365.com",
  port: 587,
  secure: false,
  auth: { user: FROM_EMAIL, pass: FROM_PASS },
});

exports.send2FACode = functions.https.onCall(async (data, context) => {
  const { email, uid } = data;
  if (!email || !uid) {
    throw new functions.https.HttpsError("invalid-argument", "Email and UID required");
  }

  // Generate 6-digit code
  const code = Math.floor(100000 + Math.random() * 900000).toString();

  // Save in Firestore with expiration (10 minutes)
  await db.collection("twoFactorCodes").doc(uid).set({
    code,
    expiresAt: new Date(Date.now() + 10 * 60 * 1000),
    used: false,
    createdAt: FieldValue.serverTimestamp(),
  });

  // Send email via your existing transporter
  await transporter.sendMail({
    from: `"DMT CMS" <${FROM_EMAIL}>`,
    to: email,
    subject: "Your DMT CMS 2FA Code",
    text: `Your verification code is: ${code}. It expires in 10 minutes.`,
  });

  console.log(`✅ 2FA code sent to ${email}`);
  return { success: true };
});

exports.sendEmailOnNewCorr = onDocumentCreated("corrs/{corrId}", async (event) => {
  const snap = event.data;
  const data = snap.data();
  const id = event.params.corrId;

  if (!data) {
    console.log("No data found in new document");
    return;
  }

  const recipients = Array.isArray(data.assignedEmails) ? data.assignedEmails : [];

  if (recipients.length === 0) {
    console.log("No assignedEmails → skipping email.");
    return;
  }

  const mailOptions = {
    from: FROM_EMAIL,
    to: recipients,
    subject: `New Correspondence: ${data.subject || "(No Subject)"} | ID: ${id}`,
    html: `
      <h4>New Correspondence Created</h4>
      <h3>Subject:</strong> ${data.subject || "N/A"}</h3>
      <p>Type of Correspondence: <strong>${data.type}</strong></p>
      <p>Priority <strong>${data.priority}</strong></p>
      <p><strong>Details:</strong></p>
      <p>${data.details || "N/A"}</p>
      <hr>

  <p>
    <a href="https://cms.camdendiocese.org">
      View This Correspondence
    </a>
  </p>

  <p>
    <a href="mailto:crm@employee.camdendiocese.org?subject=ID:${id}">
      Respond to this Correspondence Now
    </a>
  </p>

  <hr>

  <p>
    This email was automatically generated by the 
    <a href="https://cms.camdendiocese.org">Diocesan Correspondence System</a>.
  </p>
    `
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log("✅ Email sent to:", recipients);
  } catch (err) {
    console.error("❌ Failed to send email:", err);
  }
});


// Send email when a new reply is added
exports.sendEmailOnNewReply = onDocumentCreated("replies/{replyId}", async (event) => {
  const snap = event.data;
  const data = snap.data();

  if (!data) return;

  console.log("🔔 New reply detected:", data);

  const corrId = data.corrId;
  if (!corrId) {
    console.log("❌ Reply missing corrId — skipping email.");
    return;
  }

  // Get parent correspondence
  const corrDoc = await db.collection("corrs").doc(corrId).get();
  const corr = corrDoc.exists ? corrDoc.data() : {};
  if (!corr) {
    console.log("❌ Correspondence not found for ID:", corrId);
    return;
  }

  // Normalize assignedEmails
  let assignedEmails = [];
  if (Array.isArray(data.assignedEmails)) {
    assignedEmails = data.assignedEmails;
  } else if (typeof data.assignedEmails === "string") {
    assignedEmails = data.assignedEmails.split(",").map(e => e.trim());
  } else if (Array.isArray(corr.assignedEmails)) {
    assignedEmails = corr.assignedEmails;
  }

  const agentEmail = data.agentEmail || corr.agentEmail || "";
  const createdByEmail = data.createdByEmail || "";

  // Combine recipients and remove duplicates & sender
  const recipients = [...new Set([
    ...assignedEmails,
    ...(agentEmail ? [agentEmail] : [])
  ])].filter(email => email !== createdByEmail);

  if (recipients.length === 0) {
    console.log("⚠ No recipients to notify — skipping email.");
    return;
  }

  const subject = `New Reply Added: ${data.subject || corr.subject || "Correspondence Update"}`;
  const body = `
    <h2>New Reply Added</h2>
    <h3>${data.subject || corr.subject || "N/A"}</h3>
    <p><strong>Reply:</strong></p>
    <p>${data.reply || "(No reply text)"}</p>
    <p><strong>Created By:</strong> ${data.createdBy || createdByEmail || "N/A"}</p>
    <hr>
    <p><a href="https://cms.camdendiocese.org/corr/${corrId}">View Correspondence</a></p>
    <hr>
    <p>This email was automatically generated by the Diocesan Correspondence System.</p>
  `;

  try {
    await transporter.sendMail({
      from: FROM_EMAIL,
      to: recipients,
      cc: "webguy@camdendiocese.org",
      subject,
      html: body,
    });
    console.log("✅ Email sent to:", recipients);
  } catch (err) {
    console.error("❌ Failed to send email:", err);
  }
});


// -----------------------------
// 2️⃣ Scheduled IMAP fetch from inbox
// -----------------------------
const imapConfig = {
  user: imapUser,
  password: imapPass,
  host: "cloudhost-76525.us-midwest-1.nxcli.net",
  port: 993,
  tls: true,
};

async function fetchEmails() {
  return new Promise((resolve, reject) => {
    const imap = new Imap(imapConfig);

    function openInbox(cb) {
      imap.openBox("INBOX", false, cb);
    }

    imap.once("ready", () => {
      openInbox(async (err) => {
        if (err) return reject(err);

        imap.search(["UNSEEN"], (err, results) => {
          if (err) return reject(err);
          if (!results || results.length === 0) {
            console.log("No new emails found.");
            imap.end();
            return resolve();
          }

          const f = imap.fetch(results, { bodies: "", markSeen: true });

          f.on("message", (msg) => {
            msg.on("body", async (stream) => {
              try {
                const parsed = await simpleParser(stream);
                const subject = parsed.subject?.trim() || "";
                const fromEmail =
                  parsed.from?.value?.[0]?.address || "unknown@example.com";
                const receivedAt = parsed.date
                  ? new Date(parsed.date)
                  : new Date();

                // Check if the subject matches "ID:someCorrId"
                const idMatch = subject.match(/^ID:(\S+)$/i);

                if (idMatch) {
  const corrId = idMatch[1];

  // ✅ Get the parent corr
  const corrDoc = await db.collection("corrs").doc(corrId).get();
  if (!corrDoc.exists) {
    console.log("No corr found for ID:", corrId);
    return;
  }
  const corr = corrDoc.data();

  // ✅ Create reply with assignedEmails and agentEmail from parent corr
  const replyData = {
    reply: parsed.text || "no content in this reply",
    createdBy: "", // optional: could map email to a user
    createdAt: receivedAt,
    corrId: corrId,
    createdByEmail: fromEmail,
    assignedEmails: corr.assignedEmails || [],
    agentEmail: corr.agentEmail || "",
  };

  // ✅ Optional: add the email sender to assignedEmails for future notifications
  replyData.assignedEmails = [...new Set([...replyData.assignedEmails, fromEmail])];

  // Inside fetchEmails() where reply is created
await db.collection("replies").add(replyData);
console.log("✅ Created reply for corr:", corrId);

// ✅ Send notification email
await sendEmailOnReply(replyData);
} else {
                  // --- Create a new corr ---
    const newCorr = {
  subject: subject || "(No Subject)",
  priority: "High",
  details: parsed.text || "(No Body)",
  assignedEmails: [],
  agentEmail: fromEmail,
  dateReceived: receivedAt.toISOString(),
  addressedTo: "",
  agentName: "",
  senderContact: "",
  dueDate: '',
  createdAt: FieldValue.serverTimestamp(),
  type: "",
};

const docRef = await db.collection("corrs").add(newCorr);
await db.collection("corrs").doc(docRef.id).update({ id: docRef.id });

                  console.log("📩 Created new corr:", subject);
                }
              } catch (err) {
                console.error("Error parsing email:", err);
              }
            });
          });

          f.once("error", (err) => console.error("Fetch error:", err));
          f.once("end", () => {
            imap.end();
            resolve();
          });
        });
      });
    });

    imap.once("error", (err) => {
      console.error("IMAP connection error:", err);
      reject(err);
    });

    imap.connect();
  });
}

// Poll inbox every 5 minutes and create replies
exports.pollEmails = onSchedule("every 5 minutes", async (event) => {
  console.log("Checking inbox for new emails...");

  try {
    await fetchEmails(async (replyData) => {
      // ✅ Send email notification for this reply
      await sendEmailOnReply(replyData);
    });
  } catch (error) {
    console.error("Error fetching emails:", error);
  }
});


